export const copy = {
  nav: {
    accounts: '账号',
    apps: '应用与权限',
    system: '系统状态',
    settings: '设置',
  },
  common: {
    cancel: '取消',
    more: '了解更多',
    neverChecked: '尚未检查',
  },
  health: {
    ready: '正常',
    refreshable: '可自动刷新',
    reauthRequired: '需要登录',
    temporaryFailure: '暂时不可用',
    cliFailure: 'CLI 故障',
    unknown: '未检查',
    running: (n: number) => `运行中 · ${n}`,
  },
  setup: {
    title: '先完成一次本机初始化',
    description: '下载并校验官方 CLI。默认不接管 PATH。',
    detailHeader: 'PATH 和 --account',
    detail:
      'Agent 用 --account 选人。需要终端里直接运行 lark-cli 也走当前账号时，再到设置页开启 PATH 接管。',
    action: '一键初始化',
    done: '初始化完成。默认不接管 PATH，需要时到设置页开启。',
  },
  migration: {
    title: (n: number) => `发现 ${n} 个可导入的 Feishu CLI 账号`,
    description: '不会改原来的 CLI 配置文件。',
    detailHeader: '导入会动哪些东西？',
    detail: '凭据仍由官方 CLI 和系统钥匙串管理。导入后只是让本产品能选这个账号。',
    action: '查看并导入',
  },
  accounts: {
    title: '账号',
    description: '切换账号只影响之后新开的命令。',
    detailHeader: '正在跑的命令会怎样？',
    detail: '已经启动的命令继续用启动时的账号，不会在中途换人。托盘或本页切换，都是下一次启动才生效。',
    importLocal: '导入本机账号',
    add: '添加账号',
    current: '当前账号',
    currentTag: '当前',
    using: '正在使用',
    switchTo: '切换到此账号',
    reauth: '重新授权',
    remove: '移除',
    searchPlaceholder: '搜索账号、别名或 App',
    noMatch: '没有匹配的账号',
    detailEmpty: '在左边选一个账号',
    more: '更多',
    alias: '别名',
    aliasHint: '起一个短名字，在 --account 里更好写。',
    aliasPlaceholder: '例如：work',
    aliasSave: '保存',
    aliasClear: '清除',
    aliasSaved: '别名已保存。',
    aliasCleared: '已清除别名。',
    aliasInvalidTooLong: '别名过长（最多 64 字节）。',
    aliasInvalidChars: '别名不能包含 /、\\ 或控制字符。',
    aliasInvalidPrefix: '别名不能以 id:、alias: 或 app: 开头。',
    aliasDuplicate: '这个别名已经被其他账号使用。',
    commandLabel: '在 Agent 或终端里指定这个账号',
    copyCommand: '复制命令',
    commandCopied: '命令已复制。',
    check: '体检',
    checked: '体检完成，状态已更新。',
    scopeCount: (n: number) => `${n} 个权限`,
    appLabel: '所属 App',
    tenantLabel: '租户',
    removeTitle: '移除账号？',
    removeExternal:
      '只从本产品里去掉这个账号。原来的 Feishu CLI 登录态和钥匙串凭据还在。',
    removeManaged:
      '将注销并移除这个账号。同一 App 下的其他账号不受影响。',
    removed: '账号已移除',
    emptyTitle: '还没有账号',
    emptyDescription: '先有一个 App，再添加要使用的账号。',
    openId: (masked: string) => `Open ID · ${masked}`,
    lastVerified: (time: string) => `最近校验 · ${time}`,
    runningBanner: (n: number) => `${n} 个命令还在用这个账号。`,
    switched: '已切换，之后的 lark-cli 调用将使用新账号。',
    switchedWithRunning: (n: number) =>
      `已切换。${n} 个已启动的命令仍用原来的账号，之后的调用用新账号。`,
    healthDegraded: (name: string, detail: string) =>
      `账号「${name}」状态异常：${detail}`,
    keychainCliff: (from: number, to: number) =>
      `钥匙串槽位从 ${from} 降到 ${to}。账号名单还在。不要整表导入注册表。用恢复脚本干跑对照。`,
  },
  apps: {
    title: '应用与权限',
    description: '在这里查看每个 App 能用哪些权限。',
    detailHeader: '权限为什么不会自己变？',
    detail:
      '新账号授权时，按当前已启用的权限去申请。官方 CLI 以后新增的能力，不会自动加到已经导入的 App 上。',
    import: '导入 App',
    create: '通过官方流程创建新 App',
    emptyTitle: '还没有 App',
    emptyDescription: '导入已有 App，或走官方流程新建。',
    enabledCount: (enabled: number, total: number) => `${enabled}/${total} 已启用`,
    unusedScopes: (n: number) => `还有 ${n} 个权限未启用`,
    refresh: '重新读取权限',
    refreshed: '权限列表已更新',
    scopeSummary: '查看权限列表',
    scopeHint: '首次授权只会申请已启用的权限。未启用的不会自动向已有账号申请。',
    enabled: '已启用',
    disabled: '未启用',
    editScopes: '编辑权限',
    drawerTitle: (label: string) => `${label} 的权限`,
    coreSection: '默认核心权限',
    coreSectionHint: '审核过的常用权限，可以按需关掉。',
    advancedSection: '高级权限',
    advancedSectionHint: '默认不启用。官方 CLI 多数没有对应命令，或者范围过宽。',
    searchPlaceholder: '搜索权限',
    noMatch: '没有匹配的权限',
    selectedCount: (n: number, max: number) => `已选 ${n} / ${max}`,
    overLimit: (max: number) => `一次授权最多 ${max} 个权限，先取消一些再保存。`,
    save: '保存',
    saved: '权限已保存。',
    restoreDefault: '恢复默认',
    takeEffectTitle: '保存后要重新授权才生效',
    takeEffectHint: '已有账号的实际权限不会变。到账号页对用这个 App 的账号点「重新授权」，新权限才会申请下来。',
    goReauth: '去重新授权',
    discardTitle: '放弃刚改的权限？',
    discardHint: '这些改动还没保存，离开这里就会丢掉。',
    discardConfirm: '不保存，去授权',
    advancedConfirmTitle: '启用高级权限？',
    advancedConfirm: (reason: string) =>
      `这条默认不启用：${reason}。启用后会在下次授权时一并申请，可能让授权页面报错。`,
    moduleGroup: (module: string, enabled: number, total: number) =>
      `${module} · ${enabled}/${total}`,
  },
  system: {
    title: '系统状态',
    description: '查看本机官方 CLI 是否就绪，以及当前会用哪个账号。',
    detailHeader: '这里会检查什么？',
    detail: '只看安装、当前账号和诊断结果。不会读取系统钥匙串里的凭据内容。',
    cliTitle: '官方 CLI',
    cliMissing: '未安装',
    cliUnmanaged: '尚未安装，可点下方按钮安装',
    routeTitle: '当前账号',
    routeSelected: '已选择账号',
    routeMissing: '未选择账号',
    routeSelectedDetail: '已选择账号则新命令都用它',
    routeMissingDetail: '还没有选择账号，新命令没有默认身份',
    install: '安装 / 修复推荐版本',
    installed: '官方 CLI 已安装到推荐版本。',
    pathTakeoverOn: '已开启',
    pathTakeoverOff: '已关闭',
    pathTakeoverHint: '可在设置页开关',
    diagnose: '运行诊断',
    noDetail: '无更多说明',
    diagnoseEmptyTitle: '还没有诊断结果',
    diagnoseEmptyDescription: '点上方「运行诊断」查看本机安装、账号和 PATH 状态。',
    rollback: '回到上一个版本',
    rollbackTitle: '回到上一个版本？',
    rollbackHint: '装完新版本发现命令不能用时再点这个。会换回上一次安装的官方 CLI。',
    rolledBack: '已回到上一个官方 CLI 版本。',
  },
  settings: {
    title: '设置',
    description: '管理开机启动、PATH 接管和外观。关掉窗口只会藏到托盘，不会停止后台运行。',
    autostart: '开机自动启动',
    autostartHint: '登录系统后在托盘运行，每 15 分钟校验并按需刷新全部账号。',
    autostartOn: '已开启开机启动，登录系统后会在托盘后台运行。',
    autostartOff: '已关闭开机启动。',
    closeWindow: '关闭窗口时',
    closeWindowHint: '关掉窗口后继续在托盘运行。要退出，用托盘菜单里的“退出”。',
    stayBackground: '继续后台运行',
    pathTakeover: 'PATH 接管',
    pathTakeoverHint: '开启后，新开的终端里直接运行 lark-cli 也会用当前账号。Agent 用 --account 指定账号时不需要开。',
    pathTakeoverOn: 'PATH 接管已开启，新开的终端生效。',
    pathTakeoverOff: 'PATH 接管已关闭，新开的终端会用系统里原来的 lark-cli。',
    theme: '外观',
    themeHint: '跟随系统，或固定用浅色、深色。',
    themeSystem: '跟随系统',
    themeLight: '浅色',
    themeDark: '深色',
    running: '正在运行',
    runningHint: '开机和开始菜单应打开这一份程序。',
    runningVersion: (version: string) => `版本 ${version}`,
  },
  addAccount: {
    title: '添加账号',
    description: '选一个 App，然后扫码或用浏览器完成授权。',
    appLabel: '授权 App',
    placeholder: '选择 App',
    start: '开始授权',
    option: (brand: string, maskedId: string) => `${brand} App · ${maskedId}`,
    brandFeishu: '飞书',
    brandLark: 'Lark',
  },
  auth: {
    title: '官方 OAuth 授权',
    restart: '重新生成授权',
    banner: '本次一次性申请默认核心权限。扫码或在浏览器里确认后会自动完成，不必再点一次。',
    capabilities: '本次将申请这些权限',
    willRequestListed: '将申请以上这些权限。',
    remaining: '授权剩余时间',
    expired: '当前授权已不可继续，请重新生成授权。',
    modeAria: '授权方式',
    qr: '扫码授权',
    browser: '浏览器授权',
    qrHint: '请先在飞书/Lark 客户端切换到目标账号，再扫码确认',
    qrAlt: '飞书/Lark 官方授权二维码',
    qrExpired: '当前二维码已失效，请重新生成授权。',
    qrUnavailable: '二维码暂不可用，可重试生成，或切换到浏览器授权。',
    retryQr: '重新生成二维码',
    browserWarning:
      '浏览器当前已登录的飞书/Lark 身份，就是本次将被授权的身份。打开前请先确认账号。',
    urlLabel: '完整官方授权地址',
    copyUrl: '复制地址',
    openBrowser: '在系统浏览器中打开',
    copied: '授权地址已复制。',
    completed: '账号授权已完成。',
    duplicate: '该账号已存在，没有新增账号。',
  },
  importApp: {
    title: '导入已有 App',
    banner:
      'App Secret 只传给官方 lark-cli，不会写入本产品的数据或日志。随后由官方 CLI 存进系统钥匙串。',
    label: '显示名称',
    labelPlaceholder: '例如：公司飞书',
    appId: 'App ID',
    appIdPlaceholder: 'cli_xxx',
    secret: 'App Secret',
    brand: '品牌',
    brandAria: '导入 App 品牌',
    feishu: '飞书（Feishu）',
    lark: 'Lark International',
    submit: '导入并验证',
    done: 'App 已导入，权限列表已读取。',
  },
  createApp: {
    title: '通过官方流程创建 App',
    banner:
      '将在官方页面创建 App。凭据由官方 CLI 存进系统钥匙串，这里不会显示 App Secret。',
    label: 'App 显示名称',
    labelPlaceholder: '例如：工作区 App',
    brand: '品牌',
    brandAria: '创建 App 品牌',
    feishu: '飞书（Feishu）',
    lark: 'Lark International',
    getLink: '获取官方创建链接',
    cancelCreate: '取消创建',
    waitingBanner:
      '请复制或打开下方链接，在官方页面完成创建。出现链接表示已经开始，接下来要等官方 CLI 完成导入。',
    urlLabel: '完整官方创建链接',
    copyLink: '复制链接',
    openBrowser: '在浏览器打开',
    polling: '正在等待官方 CLI 完成…',
    copied: '创建链接已复制。',
    done: 'App 已创建并导入。',
  },
  importAccount: {
    title: '导入本机 Feishu CLI 账号',
    banner:
      '先读取本机已有的 CLI 配置。点导入并验证后，才会用官方 CLI 核对当前身份。Token 和 App Secret 一直留在系统钥匙串里。',
    defaultLocation: '默认位置',
    rescan: '重新检测',
    scanFailed: (error: string) => `检测失败：${error || '未知错误'}`,
    scanning: '正在读取默认位置的本机配置…',
    noneFound: '未在默认位置发现可导入账号，也可以在下方填写配置目录。',
    idleHint: '点击“重新检测”读取默认位置的本机配置。',
    alreadyImported: '已导入',
    importable: '可导入',
    needsCheck: '需检查',
    select: '选择',
    configDir: '官方 CLI 配置目录',
    configPlaceholder: '例如：C:\\Users\\name\\.lark-cli',
    label: 'App 显示名称',
    labelPlaceholder: '例如：公司飞书',
    localFeishu: '本机飞书',
    localLark: '本机 Lark',
    submit: '导入并验证',
    alreadyInProduct: '该账号已经导入过。',
    imported: (name: string) => `已导入并验证 ${name}`,
    brandFeishu: '飞书',
    brandLark: 'Lark',
  },
} as const;
